version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    container_name: app
    volumes:
            - .:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app/app.py
    command: flask run --host=0.0.0.0
